version: '3'
services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - server

  server:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - static-data:/server/static

volumes:
 static-data: