# Generated by Django 4.2.5 on 2023-09-28 09:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_user_is_deleted"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="profile_image",
            field=models.URLField(blank=True, default="", verbose_name="profile image"),
        ),
    ]
