# Generated by Django 4.2.5 on 2023-10-07 11:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_test"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Test",
        ),
    ]
