# Generated by Django 4.2.5 on 2023-10-17 13:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_delete_test"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="social_id",
            field=models.CharField(max_length=63, verbose_name="social id"),
        ),
    ]
