# Generated by Django 4.2.5 on 2023-11-18 04:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Place",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated_at"),
                ),
                ("name", models.CharField(max_length=31, verbose_name="name")),
            ],
            options={
                "verbose_name": "place",
                "verbose_name_plural": "places",
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="Seat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("column", models.CharField(max_length=3, verbose_name="column")),
                ("row", models.CharField(max_length=7, verbose_name="row")),
                (
                    "place",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="seats",
                        to="places.place",
                        verbose_name="place",
                    ),
                ),
            ],
            options={
                "verbose_name": "seat",
                "verbose_name_plural": "seats",
                "ordering": ["-id"],
            },
        ),
    ]
