# Generated by Django 4.2.5 on 2023-10-16 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("arts", "0002_ticket_alter_art_options_alter_artschedule_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Place",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated_at"),
                ),
                ("name", models.CharField(max_length=31, verbose_name="name")),
            ],
            options={
                "verbose_name": "place",
                "verbose_name_plural": "places",
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="Seat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("column", models.CharField(max_length=3, verbose_name="column")),
                ("row", models.CharField(max_length=7, verbose_name="row")),
                (
                    "place",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="seats",
                        to="places.place",
                        verbose_name="place",
                    ),
                ),
                (
                    "ticket",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="seats",
                        to="arts.ticket",
                        verbose_name="ticket",
                    ),
                ),
            ],
            options={
                "verbose_name": "seat",
                "verbose_name_plural": "seats",
                "ordering": ["-id"],
            },
        ),
    ]
