# Generated by Django 4.2.5 on 2023-10-07 11:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ArtSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_time", models.TimeField(verbose_name="start time")),
                ("end_time", models.TimeField(verbose_name="end time")),
            ],
        ),
        migrations.CreateModel(
            name="Art",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated_at"),
                ),
                ("title", models.CharField(max_length=31, verbose_name="title")),
                ("image", models.ImageField(upload_to="arts", verbose_name="image")),
                (
                    "genre",
                    models.CharField(
                        choices=[
                            ("THEA", "연극"),
                            ("MUSI", "뮤지컬"),
                            ("CONC", "콘서트"),
                            ("DANC", "무용"),
                            ("CHIL", "아동"),
                            ("PREV", "시사회"),
                            ("EXHI", "전시"),
                            ("FEST", "축제"),
                            ("LECT", "강의"),
                        ],
                        max_length=7,
                        verbose_name="genre",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[("EXHI", "전시"), ("SHOW", "공연")],
                        max_length=7,
                        verbose_name="category",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PEND", "검수중"),
                            ("REJECTED", "거부"),
                            ("APPROVED", "허용"),
                        ],
                        default="PEND",
                        max_length=15,
                        verbose_name="status",
                    ),
                ),
                (
                    "running_time",
                    models.PositiveIntegerField(default=0, verbose_name="running time"),
                ),
                (
                    "age_limit",
                    models.PositiveIntegerField(default=0, verbose_name="age limit"),
                ),
                (
                    "inter_mission",
                    models.PositiveIntegerField(
                        default=0, verbose_name="inter mission"
                    ),
                ),
                ("description", models.TextField(verbose_name="description")),
                (
                    "caution_description",
                    models.TextField(verbose_name="caution description"),
                ),
                (
                    "cs_phone_number",
                    phonenumber_field.modelfields.PhoneNumberField(
                        max_length=128, region=None
                    ),
                ),
                ("start_date", models.DateField(verbose_name="start date")),
                ("end_date", models.DateField(verbose_name="end date")),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="arts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="create by",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
