# Generated by Django 4.2.5 on 2023-11-18 04:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("arts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="art",
            name="category",
            field=models.CharField(
                choices=[("EXHIBITION", "전시"), ("SHOW", "공연")],
                max_length=15,
                verbose_name="category",
            ),
        ),
    ]
