# Generated by Django 4.2.5 on 2023-12-19 10:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("arts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="qr_code",
            field=models.ImageField(blank=True, null=True, upload_to="media/qr"),
        ),
    ]
