# Generated by Django 4.2.5 on 2023-10-16 12:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("arts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ticket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("is_reserved", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "ticket mater data",
                "verbose_name_plural": "ticket master data",
                "ordering": ["-id"],
            },
        ),
        migrations.AlterModelOptions(
            name="art",
            options={
                "ordering": ["-id"],
                "verbose_name": "art",
                "verbose_name_plural": "arts",
            },
        ),
        migrations.AlterModelOptions(
            name="artschedule",
            options={
                "ordering": ["-id"],
                "verbose_name": "art schedule",
                "verbose_name_plural": "art schedules",
            },
        ),
        migrations.AddField(
            model_name="art",
            name="is_free",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="art",
            name="limit_purchase_count",
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
