# Generated by Django 4.2.5 on 2023-11-18 05:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("arts", "0002_alter_art_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="art",
            name="status",
            field=models.CharField(
                choices=[("PENDING", "검수중"), ("REJECTED", "거부"), ("APPROVED", "허용")],
                default="PENDING",
                max_length=15,
                verbose_name="status",
            ),
        ),
    ]
