# Generated by Django 4.2.5 on 2023-10-16 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("arts", "0002_ticket_alter_art_options_alter_artschedule_options_and_more"),
        ("places", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="art",
            name="place",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="arts",
                to="places.place",
                verbose_name="place",
            ),
        ),
        migrations.AddField(
            model_name="artschedule",
            name="art",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="art_schedules",
                to="arts.art",
                verbose_name="art schedule",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="ticket",
            name="art",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tickets",
                to="arts.art",
                verbose_name="create by",
            ),
        ),
    ]
