# Generated by Django 4.2.5 on 2023-12-19 11:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("arts", "0002_ticket_qr_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="is_sold_out",
            field=models.BooleanField(default=False, verbose_name="is sold out"),
        ),
    ]
