# Generated by Django 4.2.5 on 2023-12-19 11:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("arts", "0003_ticket_is_sold_out"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="qr_code",
            field=models.ImageField(blank=True, default="", upload_to="media/qr"),
        ),
    ]
