# Generated by Django 4.2.5 on 2023-11-18 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("arts", "0003_alter_art_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="artschedule",
            name="art",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="schedules",
                to="arts.art",
                verbose_name="art schedule",
            ),
        ),
    ]
