# Generated by Django 4.2.5 on 2023-12-19 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("arts", "0004_alter_ticket_qr_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="art_schedule",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tickets",
                to="arts.artschedule",
                verbose_name="create by",
            ),
            preserve_default=False,
        ),
    ]
