# Generated by Django 4.2.5 on 2023-11-18 07:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("arts", "0004_alter_artschedule_art"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="artschedule",
            constraint=models.UniqueConstraint(
                fields=("art", "start_at"), name="unique schedule start at"
            ),
        ),
        migrations.AddConstraint(
            model_name="artschedule",
            constraint=models.UniqueConstraint(
                fields=("art", "end_at"), name="unique schedule end at"
            ),
        ),
    ]
