# Generated by Django 4.2.5 on 2024-01-18 09:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("arts", "0006_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="art",
            name="seat_max_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
