# Generated by Django 4.2.5 on 2024-01-18 09:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("arts", "0007_art_seat_max_count"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="artschedule",
            name="seat_count",
        ),
    ]
