# Generated by Django 4.2.5 on 2024-01-18 10:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("arts", "0008_remove_artschedule_seat_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="score",
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
