# Generated by Django 4.2.5 on 2024-01-18 10:54

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):
    dependencies = [
        ("arts", "0009_comment_score"),
    ]

    operations = [
        migrations.AlterField(
            model_name="art",
            name="cs_phone_number",
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
    ]
