# Generated by Django 4.2.5 on 2024-01-21 08:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("arts", "0010_alter_art_cs_phone_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="art",
            name="hit_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
