# Generated by Django 4.2.5 on 2024-01-29 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("arts", "0011_art_hit_count"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="art_schedule",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tickets",
                to="arts.artschedule",
                verbose_name="art schedule",
            ),
        ),
    ]
